steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Unit Tests
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
